[project]
name = "firstmodel"
version = "0.1.0"
authors = [
    {name = "Zack Sample", email = "samplez1@montclair.edu"},
]
description = "Package for running content modeling experiments."

[project.scripts]
run_cs_experiment = "firstmodel.run_experiment:main"
